apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: null
  name: test-pdb02
  annotations:
    pdb-description: "PDB with percentage minAvailable"
spec:
  minAvailable: "1%"
  selector:
    matchLabels:
      app: test-deploy02
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
